backend:
  name: git-gateway
  branch: scroll-cms # Branch to update (optional; defaults to master)

media_folder: "static/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "news" # Used in routes, e.g., /admin/collections/blog
    label: "News" # Used in the UI
    folder: "content/news" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Sideline", name: "sideline", widget: "string"}
      - {label: "Side Color", name: "sidecolor", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Background Pos", name: "background", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Button Color", name: "bcolor", widget: "string", default: "white"}
      - {label: "Stats", name: "stats", widget: "object", fields: [
          {label: "Name", name: "name", widget: string},
          {label: "Camera", name: "camera", widget: string},
          {label: "Lens", name: "lens", widget: string},
          {label: "Aperture", name: "aperture", widget: string},
          {label: "Focal Length", name: "focal", widget: string},
          {label: "Lighting", name: "lighting", widget: string},
          {label: "Heads", name: "heads", widget: string},
          {label: "Notes", name: "notes", widget: "text"}]}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "projects" # Used in routes, e.g., /admin/collections/blog
    label: "Projects" # Used in the UI
    folder: "content/projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Sideline", name: "sideline", widget: "string"}
      - {label: "Side Color", name: "sidecolor", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Background Pos", name: "background", widget: "string"}
      - {label: "Button Color", name: "bcolor", widget: "string", default: "white"}
      - {label: "Text Color", name: "textcolor", widget: "string", default: "white"}
      - {label: "Overlay Color", name: "readerbg", widget: "string", default: "bg-black-30"}
      - {label: "Studio", name: "studio", widget: "object", fields: [
          {label: "Client", name: "client", widget: string},
          {label: "Model", name: "model", widget: string},
          {label: "Photographer", name: "photographer", widget: string},
          {label: "Stylist", name: "stylist", widget: string},
          {label: "Studio", name: "studio", widget: string},
          {label: "Lighting", name: "lighting", widget: string},
          {label: "Heads", name: "heads", widget: string},
          {label: "Notes", name: "notes", widget: "text"}]}
      - {label: "Gallery", name: "slides", widget: "list", field:
          {label: "Image", name: "image", widget: image}}
      - {label: "Body", name: "body", widget: "markdown"}

